// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrezzeCloud.Catalog.Infrastructure.Data;

#nullable disable

namespace TrezzeCloud.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260522142531_UpdateUserLibrarySeedSingleTestUser")]
    partial class UpdateUserLibrarySeedSingleTestUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrezzeCloud.Catalog.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Category = "RPG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RPG de aventura em ilhas flutuantes com foco em exploração.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/skyward-legends.jpg",
                            IsActive = true,
                            Price = 129.90m,
                            Title = "Skyward Legends"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Category = "Racing",
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Corridas urbanas de alta velocidade com trilha eletrônica intensa.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/neon-sprint.jpg",
                            IsActive = true,
                            Price = 89.90m,
                            Title = "Neon Sprint"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Category = "Strategy",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Estratégia tática por turnos com batalhas em larga escala.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/iron-tactics.jpg",
                            IsActive = true,
                            Price = 99.50m,
                            Title = "Iron Tactics"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Category = "Simulation",
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Simulação de fazenda mágica com crafting e missões cooperativas.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/mystic-valley.jpg",
                            IsActive = true,
                            Price = 74.00m,
                            Title = "Mystic Valley"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Category = "Adventure",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thriller sci-fi com investigação em uma estação submersa.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/deep-signal.jpg",
                            IsActive = true,
                            Price = 109.00m,
                            Title = "Deep Signal"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Category = "Sandbox",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sandbox criativo de construção modular em mundos procedurais.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/block-forge.jpg",
                            IsActive = true,
                            Price = 59.90m,
                            Title = "Block Forge"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Category = "MOBA",
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "MOBA competitivo com heróis de classes assimétricas.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/shadow-arena.jpg",
                            IsActive = true,
                            Price = 0.00m,
                            Title = "Shadow Arena"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Category = "Shooter",
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "FPS tático com foco em objetivos e comunicação em equipe.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/crimson-protocol.jpg",
                            IsActive = true,
                            Price = 119.99m,
                            Title = "Crimson Protocol"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Category = "Action",
                            CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Metroidvania sombrio com progressão por habilidades.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/echoes-of-ruin.jpg",
                            IsActive = true,
                            Price = 94.49m,
                            Title = "Echoes of Ruin"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Category = "Management",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gerenciamento de colônia espacial com economia dinâmica.",
                            ImageUrl = "https://cdn.trezzecloud.local/catalog/games/orbit-colony.jpg",
                            IsActive = true,
                            Price = 139.00m,
                            Title = "Orbit Colony"
                        });
                });

            modelBuilder.Entity("TrezzeCloud.Catalog.Domain.Entities.UserLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("UserLibraries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            GameId = new Guid("11111111-1111-1111-1111-111111111101"),
                            PurchasedAt = new DateTime(2026, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            GameId = new Guid("11111111-1111-1111-1111-111111111102"),
                            PurchasedAt = new DateTime(2026, 2, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            GameId = new Guid("11111111-1111-1111-1111-111111111103"),
                            PurchasedAt = new DateTime(2026, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            GameId = new Guid("11111111-1111-1111-1111-111111111104"),
                            PurchasedAt = new DateTime(2026, 2, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            GameId = new Guid("11111111-1111-1111-1111-111111111105"),
                            PurchasedAt = new DateTime(2026, 2, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
